version: 0.2

phases:
  install:
    runtime_versions:
      - python: 3.8
    commands:
      - pip3 install -r requirements.txt
      - chmod +x sc.bash
      - apt-get update && apt-get install -y cifs-utils
  build:
    commands:
      - bash -x sc.bash
